name: lone CI

on:
  workflow_dispatch:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_lone_env:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose build lone_env
    - name: Run tox (install, lint, test)
      run: docker compose run lone_env /usr/bin/python3 -m tox -c /opt/lone/
